#!/usr/bin/env Rscript
suppressPackageStartupMessages({
  library(CellChat); library(Matrix); library(data.table); library(ggplot2)
})
args <- commandArgs(trailingOnly=TRUE)
if(length(args)<1) stop('Usage: Rscript 09_run_cellchat_stratum.R <group>')
label <- args[[1]]
valid <- c('young_female','aged_female','young_male','aged_male')
if(!label %in% valid) stop('Invalid group: ',label)
root <- 'D:/vscode/Jin2025_AgingMouseBrain'
in_dir <- file.path(root,'data/cellchat_complete/stratified',label)
out_dir <- file.path(root,'results/cellchat_complete',label)
dir.create(out_dir,recursive=TRUE,showWarnings=FALSE)
log_file <- file.path(out_dir,'run.log')
sink(log_file,split=TRUE)
on.exit({sink()},add=TRUE)
set.seed(20260704)
cat('CellChat stratum:',label,'\n'); cat('CellChat version:',as.character(packageVersion('CellChat')),'\n')
counts <- as(readMM(gzfile(file.path(in_dir,'counts.mtx.gz'))),'dgCMatrix')
genes <- fread(file.path(in_dir,'genes.csv'))[[1]]
meta <- fread(file.path(in_dir,'metadata.csv'),data.table=FALSE)
stopifnot(nrow(counts)==length(genes),ncol(counts)==nrow(meta),!anyDuplicated(meta$cell_label))
rownames(counts)<-genes; colnames(counts)<-meta$cell_label; rownames(meta)<-meta$cell_label
lib <- Matrix::colSums(counts); if(any(lib==0)) stop('Zero-library cells detected')
norm <- counts %*% Diagonal(x=1e4/lib); norm@x <- log1p(norm@x); dimnames(norm) <- list(genes, meta$cell_label); stopifnot(identical(colnames(norm), rownames(meta)))
rm(counts); gc()
cc <- createCellChat(object=norm,meta=meta,group.by='cell_type_major')
cc@DB <- CellChatDB.mouse
cc <- subsetData(cc)
cat('Cells:',ncol(norm),' groups:',length(levels(cc@idents)),' signaling genes:',nrow(cc@data.signaling),'\n')
cc <- identifyOverExpressedGenes(cc)
cc <- identifyOverExpressedInteractions(cc)
saveRDS(cc,file.path(out_dir,'checkpoint_overexpression.rds'),compress=FALSE)
cc <- computeCommunProb(cc,type='triMean',raw.use=TRUE,population.size=FALSE,nboot=100,seed.use=20260704)
cc <- filterCommunication(cc,min.cells=30)
cc <- computeCommunProbPathway(cc)
cc <- aggregateNet(cc)
cc <- tryCatch(netAnalysis_computeCentrality(cc,slot.name='netP'),error=function(e){cat('Centrality warning:',conditionMessage(e),'\n');cc})
saveRDS(cc,file.path(out_dir,paste0('cellchat_',label,'.rds')),compress=FALSE)
lr <- subsetCommunication(cc,slot.name='net'); path <- subsetCommunication(cc,slot.name='netP')
fwrite(lr,file.path(out_dir,'lr_interactions.csv')); fwrite(path,file.path(out_dir,'pathway_interactions.csv'))
fwrite(as.data.frame(as.table(cc@net$count)),file.path(out_dir,'network_count.csv'))
fwrite(as.data.frame(as.table(cc@net$weight)),file.path(out_dir,'network_weight.csv'))
tg <- lr[grepl('TGF',lr$interaction_name_2,ignore.case=TRUE)|grepl('TGF',lr$ligand,ignore.case=TRUE)|grepl('TGF',lr$receptor,ignore.case=TRUE),]
fwrite(tg,file.path(out_dir,'tgfb_lr_interactions.csv'))
pdf(file.path(out_dir,'network_heatmaps.pdf'),width=14,height=7)
print(netVisual_heatmap(cc,measure='count',title.name=paste(label,'interaction count')))
print(netVisual_heatmap(cc,measure='weight',title.name=paste(label,'interaction weight')))
dev.off()
summary <- data.frame(group=label,cells=ncol(norm),cell_types=length(levels(cc@idents)),signaling_genes=nrow(cc@data.signaling),lr_rows=nrow(lr),pathway_rows=nrow(path),total_count=sum(cc@net$count),total_weight=sum(cc@net$weight),stringsAsFactors=FALSE)
fwrite(summary,file.path(out_dir,'run_summary.csv'))
cat('Completed:',label,' LR=',nrow(lr),' pathways=',length(cc@netP$pathways),'\n')
